function smallEnough(a, limit){
  for (i = 0; i < a.length; i++){ // For every number in array a...
    if (a[i] > limit) {           // if that number is greater than the limit...
      return false;               // the result is false
    }
  }                               // If the entire array is less than or equal to the limit...
  return true;                    // the result is true
}     
